/**
 * Renders ARCHITECTURE_REPORT.md from the analysis model.
 */
export function buildReport(model) {
  const M = model.metrics;
  const L = model.lines = [];
  const w = (s = "") => L.push(s);

  const table = (headers, rows) => {
    w("| " + headers.join(" | ") + " |");
    w("| " + headers.map(() => "---").join(" | ") + " |");
    for (const r of rows) w("| " + r.join(" | ") + " |");
    w();
  };
  const code = (s) => "`" + s + "`";

  w(`# Architecture Report`);
  w();
  w(`> ${model.generatedAt} · project **${model.root}** · generated by the Graphify toolchain (\`npm run graph\`).`);
  w(`> Scope: first-party modules under \`src/\`. Third-party packages are counted as external fan-out but not traversed.`);
  w();

  // ---- Overview -------------------------------------------------------
  w(`## 1. Overview`);
  w();
  table(
    ["Metric", "Value"],
    [
      ["Files / nodes", M.nodeCount],
      ["Import edges", M.edgeCount],
      ["– dynamic / lazy edges", M.dynamicEdges],
      ["– type-only edges", M.typeOnlyEdges],
      ["Average degree", M.avgDegree],
      ["Average fan-out", M.avgFanOut],
      ["Connected components", M.connectedComponents],
      ["Largest connected component", M.largestComponentSize],
      ["Strongly connected components", M.stronglyConnectedComponents],
      ["**Circular dependency groups**", `**${M.circularGroupCount}**`],
      ["Detected clusters (communities)", M.communityCount],
      ["Longest dependency chain (depth)", M.maxDepth],
      ["Orphan modules", M.orphanCount],
      ["Modules with no importers", M.deadCandidateCount],
      ["Modules reading env/config", M.envAccessCount],
    ]
  );

  const health =
    M.circularGroupCount === 0 && M.orphanCount <= 2
      ? "🟢 **Healthy** — no circular dependencies and few orphans."
      : M.circularGroupCount === 0
      ? "🟡 **Good** — no circular dependencies; review orphan/unused modules below."
      : "🔴 **Attention** — circular dependencies present; see section 4.";
  w(health);
  w();

  // ---- Layers ---------------------------------------------------------
  w(`## 2. Layer composition`);
  w();
  table(
    ["Layer", "Files", "Total degree", "Avg degree"],
    model.layers.map((l) => [l.key, l.count, l.totalDegree, (l.totalDegree / l.count).toFixed(1)])
  );

  w(`## 3. Module clusters`);
  w();
  w(`Label-propagation community detection found **${M.communityCount} clusters**. Clusters group modules that import each other densely — ideally they line up with feature folders. Colour the graph by **Cluster** to inspect them.`);
  w();
  const folderRows = model.folders
    .slice(0, 12)
    .map((f) => [code(f.key), f.count, f.totalDegree]);
  table(["Folder", "Files", "Total degree"], folderRows);

  // ---- Circular -------------------------------------------------------
  w(`## 4. Circular dependencies`);
  w();
  if (!model.circular.length) {
    w(`✅ **None detected.** No strongly-connected group larger than a single module. Import direction is acyclic.`);
    w();
  } else {
    w(`Found **${model.circular.length}** circular group(s). These create tight coupling, complicate tree-shaking, and can trigger \`undefined\` at module init. Break them by extracting shared code into a leaf module or inverting one dependency.`);
    w();
    for (const c of model.circular) {
      w(`### Cycle #${c.id} — ${c.size} modules`);
      w();
      for (const mm of c.members) w(`- ${code(mm)}`);
      w();
      if (c.cycleEdges.length) {
        w("Edges inside the cycle:");
        w();
        for (const [a, b] of c.cycleEdges) w(`- ${code(a)} → ${code(b)}`);
        w();
      }
    }
  }

  // ---- Hotspots -------------------------------------------------------
  w(`## 5. Hotspots`);
  w();
  w(`### Highest coupling (degree = fan-in + fan-out)`);
  w();
  table(
    ["Module", "In", "Out", "Degree", "Layer"],
    model.hotspots.coupling.map((n) => [code(n.label), n.fanIn, n.fanOut, n.degree, n.layer])
  );
  w(`### Highest fan-in (most depended-upon — a change here ripples widest)`);
  w();
  table(
    ["Module", "Fan-in", "Layer"],
    model.hotspots.fanIn.map((n) => [code(n.label), n.fanIn, n.layer])
  );
  w(`### Highest fan-out (imports the most — candidate "God" modules)`);
  w();
  table(
    ["Module", "Fan-out", "Ext pkgs", "Layer"],
    model.hotspots.fanOut.map((n) => [code(n.label), n.fanOut, n.externalCount, n.layer])
  );
  w(`### Deepest dependency chains`);
  w();
  table(
    ["Module", "Downstream depth", "Layer"],
    model.hotspots.deepest.map((n) => [code(n.label), n.depth, n.layer])
  );

  // ---- Dead / orphan --------------------------------------------------
  w(`## 6. Orphans & dead-code candidates`);
  w();
  w(`**Orphans** import nothing and are imported by nothing (fully disconnected).`);
  w();
  if (!model.orphans.length) w(`✅ None.`);
  else for (const n of model.orphans) w(`- ${code(n.label)} — _${n.type}_`);
  w();
  w(`**No-importer modules** have zero first-party importers. Some are legitimately entry-like (mounted via the router, loaded lazily, or consumed only by tooling); verify before deleting.`);
  w();
  if (!model.deadCandidates.length) w(`✅ None.`);
  else
    table(
      ["Module", "Type", "Fan-out"],
      model.deadCandidates.map((n) => [code(n.label), n.type, n.fanOut])
    );

  // ---- Recommendations ------------------------------------------------
  w(`## 7. Recommendations`);
  w();
  const recs = [];
  if (M.circularGroupCount > 0)
    recs.push([`P1`, `Break the ${M.circularGroupCount} circular group(s) in section 4 by extracting shared types/helpers into a leaf module.`]);
  const godFanOut = model.hotspots.fanOut[0];
  if (godFanOut && godFanOut.fanOut >= 12)
    recs.push([`P2`, `${code(godFanOut.label)} has fan-out ${godFanOut.fanOut}. If it is a component, split it into subcomponents/hooks; if a barrel, keep it, but audit for accidental over-import.`]);
  const hub = model.hotspots.fanIn[0];
  if (hub && hub.fanIn >= 10)
    recs.push([`P2`, `${code(hub.label)} is imported ${hub.fanIn}×. Treat it as a stable public API — changes here are high-blast-radius, so cover it with tests and avoid breaking signatures.`]);
  if (M.deadCandidateCount > 0)
    recs.push([`P3`, `Review the ${M.deadCandidateCount} no-importer module(s) in section 6; delete or wire up genuinely unused ones to shrink the bundle.`]);
  if (M.orphanCount > 0)
    recs.push([`P3`, `Investigate ${M.orphanCount} orphan module(s) — usually leftover scaffolding.`]);
  if (M.communityCount > 0 && model.folders.length > 0)
    recs.push([`P4`, `Compare clusters (colour-by-cluster in the graph) against folders. A cluster that spans many folders signals a cross-cutting concern worth isolating.`]);
  if (!recs.length) recs.push([`P4`, `No structural issues detected. Keep the graph in CI to catch regressions.`]);

  table(["Priority", "Action"], recs);

  w(`## 8. How to read the graph`);
  w();
  w(`Open ${code("graph/graph.html")} in any browser (no server needed).`);
  w();
  w(`- **Node size** ∝ degree (coupling). Big nodes are architectural hubs.`);
  w(`- **Colour** = layer (default), folder, or detected cluster — toggle top-left.`);
  w(`- **Click** a node to pin it: <span>blue</span> = incoming (who imports it), orange = outgoing (what it imports). Use the **Neighbor depth** slider for transitive reach.`);
  w(`- **Dashed edges** = dynamic / lazy imports (\`React.lazy\`, \`import()\`).`);
  w(`- **Highlight issues** toggles surface circular, orphan, dead-code and env-access nodes.`);
  w(`- **Search** filters by filename; **Fit** / **Reset** / **Reheat** control the camera & physics.`);
  w();
  w(`---`);
  w(`<sub>Regenerate: ${code("npm run graph")} · watch mode: ${code("npm run graph:watch")} · report only: ${code("npm run graph:report")}</sub>`);

  return L.join("\n") + "\n";
}
