// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://twwgtymepiplbcwcvggo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR3d2d0eW1lcGlwbGJjd2N2Z2dvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQzOTUwNjIsImV4cCI6MjA4OTk3MTA2Mn0.sbwOCG3kPOlEQ-foRBdgA1UXY6GMtEre3HxdCsLXUkE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});